language: python

python:
  - 2.7
  
build:
  ci:
    - echo "$KUBECONFIG_MANISHAS_INTEGRATION_KUBECONFIGCONTENT"
    - echo "$KUBECONFIG_MANISHAS_INTEGRATION_KUBECONFIG"
    - echo "$KUBECONFIG_MANISHAS_INTEGRATION_KUBECONFIGFILE"  
    - echo "$KUBECONFIG_INTEGRATION_KUBECONFIG_MANISHAS_INTEGRATION_KUBECONFIGCONTENT"
    - echo "$KUBECONFIG_INTEGRATION_KUBECONFIG_MANISHAS_INTEGRATION_KUBECONFIG"
    - echo "$KUBECONFIG_INTEGRATION_KUBECONFIG_MANISHAS_INTEGRATION_KUBECONFIGFILE"
    - echo "$KUBECONFIG_INTEGRATION_KUBECONFIGFILE"
    - echo "$KUBECONFIG_INTEGRATION_KUBECONFIGCONTENT"
    - echo "$KUBECONFIG_INTEGRATION_KUBECONFIG"

resources:
  - name: kubeconfig
    type: integration
    integration: kubeconfig_manishas

jobs:
  - name: testKube_runCI
    type: runCI
    steps:
      - IN: kubeconfig
