language: python

python:
  - 2.7
  
build:
  ci:
    - echo "$KUBECONFIG_INTEGRATION_KUBECONFIGCONTENT"

resources:
  - name: kubeconfig
    type: integration
    integration: kubeconfig_manishas

jobs:
  - name: testKube_runCI
    type: runCI
    steps:
      - IN: kubeconfig
